name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r restaurant_search_api/requirements.txt

    - name: Run tests
      run: |
        # Here you can add any test commands you need
        echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy Infrastructure with Terraform
      run: |
        cd infra/
        terraform init
        terraform apply -auto-approve

    - name: Deploy Application
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=RestaurantSearchAPI" --query "Reservations[*].Instances[*].InstanceId" --output text)
        PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[*].Instances[*].PublicIpAddress" --output text)
        ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ec2-user@$PUBLIC_IP << 'EOF'
          git clone https://github.com/dimaa2024/examfp.git
          cd examfp/restaurant_search_api
          pip install -r requirements.txt
          nohup python app.py &
        EOF